routes:
  dav:
    target_url: https://duocquocgia.com.vn/api/{path:path}
    timeout: 30
  vcb:
    target_url: http://119.82.141.227:18443/{path:path}
    timeout: 30

server:
  host: "0.0.0.0"
  port: 8321
  log_level: "INFO"

logging:
  rotation: "1 day"
  retention: "30 days"
  compression: "zip"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}" 