routes:
  dav:
    target_url: https://duocquocgia.com.vn/api/{path:path}
    timeout: 30
  
  # Thêm các provider khác nếu cần
  # provider_b:
  #   path: api/{path}
  #   target_url: https://provider-b.com/api/{path}
  #   timeout: 30

server:
  host: "0.0.0.0"
  port: 8000
  log_level: "INFO"

logging:
  rotation: "1 day"
  retention: "30 days"
  compression: "zip"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}" 