name: Build Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn loguru pyyaml httpx pydantic pyinstaller
    
    - name: Test imports
      run: |
        python -c "import app.main; print('Import OK')"
        python -c "from app.config import config; print('Config OK:', len(config.routes))"
    
    - name: Build executable
      run: |
        pyinstaller --onefile --console app/main.py --name forward-api-gateway
    
    - name: Create package
      run: |
        mkdir build\windows
        copy dist\forward-api-gateway.exe build\windows\
        copy config.yaml build\windows\
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable-only
        path: build/windows/ 