name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn loguru pyyaml httpx pydantic
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --console --name forward-api-gateway app/main.py --add-data "config.yaml;." --add-data "app;app" --hidden-import uvicorn.logging --hidden-import uvicorn.loops --hidden-import uvicorn.loops.auto --hidden-import uvicorn.protocols --hidden-import uvicorn.protocols.http --hidden-import uvicorn.protocols.http.auto --hidden-import uvicorn.protocols.websockets --hidden-import uvicorn.protocols.websockets.auto --hidden-import uvicorn.lifespan --hidden-import uvicorn.lifespan.on --hidden-import loguru --hidden-import yaml --hidden-import httpx --hidden-import fastapi --hidden-import starlette --hidden-import pydantic
    
    - name: Create Windows package
      run: |
        mkdir build\windows
        copy dist\forward-api-gateway.exe build\windows\
        copy config.yaml build\windows\
        copy README.md build\windows\
        
        # Create start.bat
        (
          echo @echo off
          echo echo Starting Forward API Gateway...
          echo forward-api-gateway.exe
          echo pause
        ) > build\windows\start.bat
        
        # Create install-service.bat
        (
          echo @echo off
          echo echo Installing Forward API Gateway as Windows Service...
          echo sc create "ForwardAPI" binPath="%%~dp0forward-api-gateway.exe" start=auto
          echo sc description "ForwardAPI" "Forward API Gateway Service"
          echo echo Service installed. To start: sc start ForwardAPI
          echo pause
        ) > build\windows\install-service.bat
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/windows/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 