name: Test Only

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn loguru pyyaml httpx pydantic
    
    - name: Test 1 - Python version
      run: |
        python --version
        python -c "import sys; print('Python executable:', sys.executable)"
    
    - name: Test 2 - List files
      run: |
        echo "Current directory:"
        pwd
        echo "Files:"
        dir
        echo "App directory:"
        dir app
    
    - name: Test 3 - Basic imports
      run: |
        python -c "import fastapi; print('FastAPI OK')"
        python -c "import uvicorn; print('Uvicorn OK')"
        python -c "import loguru; print('Loguru OK')"
        python -c "import yaml; print('YAML OK')"
        python -c "import httpx; print('HTTPX OK')"
        python -c "import pydantic; print('Pydantic OK')"
    
    - name: Test 4 - App imports
      run: |
        python -c "import app; print('App package OK')"
        python -c "import app.config; print('Config module OK')"
        python -c "import app.logger; print('Logger module OK')"
        python -c "import app.middleware; print('Middleware module OK')"
        python -c "import app.forwarder; print('Forwarder module OK')"
    
    - name: Test 5 - Main import
      run: |
        python -c "import app.main; print('Main module OK')"
    
    - name: Test 6 - Config loading
      run: |
        python -c "from app.config import config; print('Config loaded OK, routes:', len(config.routes))"
    
    - name: Test 7 - Run main (timeout)
      run: |
        echo "Testing main execution..."
        python app/main.py &
        $pid = $LASTEXITCODE
        Start-Sleep -Seconds 5
        Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
        echo "Main execution test completed" 